import { describe, it, expect } from 'vitest';
import { detectIntent } from '../src/modality/detect.js';
import { evalArithmetic, getDeterministicHandler, registerDeterministicHandler } from '../src/modality/deterministic.js';
import { planIntent, type PlanCtx } from '../src/modality/planner.js';
import { loadCapabilities, summarize } from '../src/modality/registry.js';
import { runMultimodal } from '../src/modality/execute.js';
import { parseMode, type Capability } from '../src/modality/types.js';

const caps = loadCapabilities({});
const ctx = (over: Partial<PlanCtx> = {}): PlanCtx => ({ modalityMode: 'on', deterministicMode: 'on', capabilities: caps, isConfigured: (p) => p === 'bailian', bandOf: () => 'green', breakerOpen: () => false, ...over });
const intent = (body: any, prompt = '', headers: Record<string, unknown> = {}) => detectIntent(body, headers, prompt);

describe('detection (deterministic)', () => {
  it('explicit fields win', () => {
    expect(intent({ modality: 'image', prompt: 'a red fox' }).output).toBe('image');
    expect(intent({ output_type: 'tts' }, 'hello').output).toBe('audio');
    expect(intent({ modalities: ['text', 'audio'] }, 'hi').output).toBe('audio');
    expect(intent({}, 'x', { 'x-output-type': 'video' }).output).toBe('video');
    expect(intent({ modality: 'hologram' }, 'x').output).toBe('text');
  });
  it('conservative heuristics: only leading imperatives', () => {
    expect(intent({}, 'Generate an image of a cat on a roof').output).toBe('image');
    expect(intent({}, 'Gere uma imagem de um gato').output).toBe('image');
    expect(intent({}, 'tts: bom dia').output).toBe('audio');
    expect(intent({}, 'Explain how an image is generated by a diffusion model').output).toBe('text');
    expect(intent({}, 'I want you to generate an image of x').output).toBe('text');
  });
  it('math heuristic is strict; dates/plain numbers/prose are not math', () => {
    expect(intent({}, '2+2').deterministic?.handler).toBe('math');
    expect(intent({}, 'calculate (3+4)*5').deterministic?.handler).toBe('math');
    expect(intent({}, '2026-10-10').deterministic).toBeNull();
    expect(intent({}, '42').deterministic).toBeNull();
    expect(intent({}, 'what is 2+2 and why').deterministic).toBeNull();
  });
  it('explicit deterministic handler via body or header', () => {
    expect(intent({ deterministic: { handler: 'json-format', input: '{"a":1}' } }).deterministic).toMatchObject({ handler: 'json-format', via: 'explicit' });
    expect(intent({}, '1', { 'x-deterministic': 'math' }).deterministic?.handler).toBe('math');
  });
  it('records media input parts', () => {
    expect(intent({ messages: [{ role: 'user', content: [{ type: 'input_audio' }] }] }).inputs).toContain('audio');
  });
});

describe('deterministic handlers', () => {
  it('math: precedence, power, parens, errors, no code execution', () => {
    expect(evalArithmetic('2+3*4')).toBe(14); expect(evalArithmetic('(2+3)*4')).toBe(20); expect(evalArithmetic('2^3^2')).toBe(512); expect(evalArithmetic('-3+5')).toBe(2); expect(evalArithmetic('7,5*2')).toBe(15);
    expect(() => evalArithmetic('1/0')).toThrow(); expect(() => evalArithmetic('process.exit()')).toThrow(); expect(() => evalArithmetic('2+')).toThrow();
  });
  it('json-format + pluggable registration', () => {
    expect(getDeterministicHandler('json-format')!.run('{"a":1}')).toEqual({ ok: true, output: '{\n  "a": 1\n}' });
    expect(getDeterministicHandler('json-format')!.run('{bad')).toMatchObject({ ok: false });
    registerDeterministicHandler({ id: 'upper', description: 't', run: (s) => ({ ok: true, output: s.toUpperCase() }) });
    expect(getDeterministicHandler('upper')!.run('ab')).toEqual({ ok: true, output: 'AB' });
  });
});

describe('planner', () => {
  it('modes default off -> llm', () => {
    expect(parseMode(undefined)).toBe('off');
    expect(planIntent(intent({ modality: 'image', prompt: 'x' }), ctx({ modalityMode: 'off', deterministicMode: 'off' })).kind).toBe('llm');
  });
  it('deterministic when matched and mode on; llm when its mode is off; error for unknown explicit handler', () => {
    expect(planIntent(intent({}, '2+2'), ctx())).toMatchObject({ kind: 'deterministic', handler: 'math' });
    expect(planIntent(intent({}, '2+2'), ctx({ deterministicMode: 'off' })).kind).toBe('llm');
    expect(planIntent(intent({ deterministic: 'nope' }, 'x'), ctx())).toMatchObject({ kind: 'error', code: 'no_deterministic_handler' });
  });
  it('image/audio go to the configured Bailian entries', () => {
    expect(planIntent(intent({ modality: 'image', prompt: 'fox' }), ctx())).toMatchObject({ kind: 'multimodal', target: { model: 'wan2.7-image' } });
    expect(planIntent(intent({ modality: 'audio', prompt: 'oi' }), ctx())).toMatchObject({ kind: 'multimodal', target: { model: 'qwen-audio-3.0-tts' } });
  });
  it('video / 3d: clear "no active provider" error, nothing invented', () => {
    for (const m of ['video', '3d']) expect(planIntent(intent({ modality: m, prompt: 'x' }), ctx())).toMatchObject({ kind: 'error', code: 'no_provider', status: 422 });
    const sum = summarize(caps, (p) => p === 'bailian');
    expect(sum.find((s) => s.modality === 'video')!.status).toBe('no_active_provider');
    expect(sum.find((s) => s.modality === '3d')!.status).toBe('no_active_provider');
    expect(sum.find((s) => s.modality === 'image')!.status).toBe('active');
  });
  it('provider not configured -> no_provider; registered-without-executor -> no_executor', () => {
    expect(planIntent(intent({ modality: 'image', prompt: 'x' }), ctx({ isConfigured: () => false }))).toMatchObject({ kind: 'error', code: 'no_provider' });
    const rt: Capability[] = [{ provider: 'p', model: 'rt', input: ['audio'], output: ['video'], endpoint: 'video', source: 'file' }];
    expect(planIntent(intent({ modality: 'video', prompt: 'x' }), ctx({ capabilities: rt, isConfigured: () => true }))).toMatchObject({ kind: 'error', code: 'no_executor', status: 501 });
  });
  it('quota: red band / breaker -> 429; alternatives ordered by band', () => {
    expect(planIntent(intent({ modality: 'image', prompt: 'x' }), ctx({ bandOf: () => 'red' }))).toMatchObject({ kind: 'error', code: 'quota_exhausted', status: 429 });
    expect(planIntent(intent({ modality: 'image', prompt: 'x' }), ctx({ breakerOpen: () => true }))).toMatchObject({ kind: 'error', code: 'quota_exhausted' });
    const two: Capability[] = [{ provider: 'a', model: 'ia', input: ['text'], output: ['image'], endpoint: 'images', source: 'file' }, { provider: 'b', model: 'ib', input: ['text'], output: ['image'], endpoint: 'images', source: 'file' }];
    const p = planIntent(intent({ modality: 'image', prompt: 'x' }), ctx({ capabilities: two, isConfigured: () => true, bandOf: (x) => (x === 'a' ? 'orange' : 'green') }));
    expect(p).toMatchObject({ kind: 'multimodal', target: { provider: 'b' } });
  });
});

describe('executors (mock fetch)', () => {
  const tgt = (endpoint: any): Capability => ({ provider: 'bailian', model: 'm', input: ['text'], output: ['image'], endpoint, source: 'file' });
  it('image: OpenAI-compatible request, key only in header, upstream error surfaces without body', async () => {
    let seen: any;
    const ok: typeof fetch = (async (u: any, init: any) => { seen = { u, init }; return new Response(JSON.stringify({ data: [{ url: 'https://x/i.png' }] }), { status: 200 }); }) as any;
    const r = await runMultimodal(tgt('images'), intent({ modality: 'image', prompt: 'fox' }), { baseUrl: 'https://h/v1/', apiKey: 'SECRET' }, { prompt: 'fox' }, ok);
    expect(r.ok).toBe(true); expect(seen.u).toBe('https://h/v1/images/generations');
    expect(seen.init.headers.Authorization).toBe('Bearer SECRET'); expect(String(seen.init.body)).not.toContain('SECRET');
    const bad: typeof fetch = (async () => new Response('secret upstream body', { status: 500 })) as any;
    const r2 = await runMultimodal(tgt('images'), intent({ modality: 'image', prompt: 'fox' }), { baseUrl: 'https://h/v1', apiKey: 'K' }, {}, bad);
    expect(r2).toMatchObject({ ok: false, status: 500, error: 'upstream 500' }); expect(JSON.stringify(r2)).not.toContain('secret upstream');
  });
  it('speech returns base64 audio; unsupported endpoint -> 501', async () => {
    const f: typeof fetch = (async () => new Response(new Uint8Array([1, 2, 3]), { status: 200, headers: { 'content-type': 'audio/mpeg' } })) as any;
    const r = await runMultimodal(tgt('speech'), intent({ modality: 'audio', prompt: 'oi' }), { baseUrl: 'https://h/v1', apiKey: 'K' }, {}, f);
    expect(r).toMatchObject({ ok: true, kind: 'audio', data: { bytes: 3 } });
    expect((await runMultimodal(tgt('realtime'), intent({}, ''), { baseUrl: 'h', apiKey: 'K' }, {}, f)).status).toBe(501);
  });
});
